### ISSUE TITLE
ERROR: appimage_get_type : Unknown AppImage format

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#102]
Getting lots of 

```
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
```

It would be useful if the filename was printed too, to make some sense of the output.

```
appimaged, continuous build (commit 2e34378), build 108 built on 2019-03-14 17:43:20 UTC
```

**Comment by probonopd** [comment]
We can now see which files are "Unknown AppImage format". Basically all files that are not AppImages, of which I have _a lot_ in my (sub)directories (next to AppImages).

Hence, a file that is not an AppImage should not throw an error or be reported on the command line (unless in special debugging mode).

https://github.com/AppImage/libappimage/blob/f3d6400ce1c33b96e8671a971ebcb0df4a63faed/src/libappimage/core/AppImage.cpp#L44

**Comment by azubieta** [comment]
should be fixed by #112

**Comment by probonopd** [comment]
Still getting this

```
ERROR: appimage_register_in_system : boost::filesystem::permissions: Operation not permitted: "/isodevice/Applications/Kdenlive-x86_64.AppImage"
ERROR: appimage_register_in_system : Unexpected char '_' at 0
ERROR: appimage_register_in_system : boost::filesystem::permissions: Operation not permitted: "/isodevice/Applications/k3b-git20170204-x86_64.AppImage"
ERROR: appimage_get_type : Unknown AppImage format: /isodevice/Applications/Slic3rPEProfiles/print/sp 0.45mm FAST 0.6 nozzle.ini
ERROR: appimage_get_type : Unknown AppImage format: /isodevice/Applications/Slic3rPEProfiles/print/sp 0.35mm FAST 0.6 nozzle.ini
```

Please always confirm using a continuous Travis CI build that the changes are actually working. Thanks!

**Comment by probonopd** [comment]
This appears to be resolved in appimaged 1c7986a, thank you.
