### ISSUE TITLE
x86 AppImage with size bigger than 2GB not working on x86_64 Linux

### ISSUE THREAD

**Issue by sigmaboy** [AppImage/libappimage#21]
When I built an large (5GB) x86 AppImage on my x86_64 openSUSE linux I get the following error when running it:
```
Cannot open /proc/self/exe: Value too large for defined data type
Failed to get fs offset for /proc/self/exe
```
It seems my image is too big. A friend of mine is using Ubuntu and for him the generated AppImage works fine.
Since it's a video game with packed size of 5GB I can't get it smaller.
I googled a lot and found out the following. Maybe I need to rebuild some of my software stack (maybe coreutils) with the following gcc option
```
 -D_FILE_OFFSET_BITS=64
```
But I think this is already activated on my whole software stack, because this is stuff which changed in like 2006. But of course I'm not sure.

I successfully built x86 appimages (also games) which are smaller than 2GB which work flawlessly. 

Strace prints the following line when executing the binary
```
[...]
open("/proc/self/exe", O_RDONLY)        = -1 EOVERFLOW (Value too large for defined data type)
write(2, "Cannot open /proc/self/exe: Valu"..., 66Cannot open /proc/self/exe: Value too large for defined data type
[...]
```

I'm using openSUSE 42.3 x86_64 with the default kernel.

If you need any more info, just ask. 
Thank you in advance

**Comment by azubieta** [comment]
Fixed at https://github.com/AppImage/libappimage/pull/20

**Comment by sigmaboy** [comment]
I dropped the issue because I had no more ideas left. @azubieta seemed to fix this but unfortunately this doesn't work for me. I still get the same error on the same filesystems. tmps, vfat and nfs still working, while the other don't. Could you maybe have another look into it. If you want, I can provide updated Appimage built with current versions of appimagetools.

**Comment by TheAssassin** [comment]
@azubieta is AppImageKit using the latest 0.1.x version of libappimage? I doubt it. Can you please update it there?

**Comment by azubieta** [comment]
@TheAssassin I don't have permissions to push to the AppImageKit master branch.

**Comment by sigmaboy** [comment]
That explained alot. But unfortunately it won't work with the latest version of libappimage.
I used the latest CI build (commit cddcc2e) which is the commit state TheAssassin made to update the git submodule.
Still the same error.
Here is a current AppImage build. It only calls a little "echo" bash script to verify it works.
https://drive.google.com/open?id=1dWXb7TJQTkrv4cyM7lb7nRKvq9YM9eoK

**Comment by sigmaboy** [comment]
@azubieta Could you maybe have another look at it?

**Comment by TheAssassin** [comment]
@azubieta tested it in a "sane" way locally and thought the issue was fixed (i.e., in a way you would write such a system test, too). However, now it seems there was another edge case found where it failed again. A test wouldn't have captured that.

What I don't like about such a test is the high amount of file I/O which would be annoying for devs. It wears down SSDs quite quickly. Also, it seems to be quite tricky to create the environment to reproduce the bug, which is also a reason against such a test. And I'd never test such things on a totally unknown environment such as Travis CI -- who knows what they configured in their kernels etc.?

**Comment by sigmaboy** [comment]
@TheAssassin @azubieta 
This is how I can reproduce the issue with a Ubuntu 18.10 Live Linux:
1. Download Ubuntu 18.10: http://cdimage.ubuntu.com/xubuntu/releases/18.10/release/xubuntu-18.10-desktop-amd64.iso
1. Boot the Xubuntu LIVE iso with KVM/libvirt with at least 4GB of RAM and internet access.
1.  Install all dependecies to run the 32bit appimage (including sshd to access the live linux via ssh)
```bash
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 libz1:i386 libfuse2:i386 openssh-server
sudo systemctl start sshd.service
sudo passwd xubuntu
```
Set the password as you wish
4. Download the following appimage to your client (not the vm): https://drive.google.com/file/d/1dWXb7TJQTkrv4cyM7lb7nRKvq9YM9eoK/view
5. Create an ext4 disk image
```bash
mkdir tmpfs
sudo mount -t tmpfs -o size=3G none tmpfs
dd if=/dev/zero of=./tmpfs/test.img bs=1M count=3072
mkfs.ext4 ./tmpfs/test.img
mkdir ext4
sudo mount ./tmpfs/test.img ext4
```
6. Copy the appimage to your Live Linux with scp
```bash
client$ scp TestApp_2019-01-23.AppImage xubuntu@10.0.0.xxx:/home/xubuntu/ext4/
```
7. On the live Linux run the appimage
```bash
./tmpfs/TestApp_2019-01-23.AppImage
```

Alternative install some linux distribution with an ext or xfs filesystem and run the appimage from there.

As written in this [comment](https://github.com/AppImage/libappimage/issues/21#issuecomment-410696769). tmpfs, nfs and (v)fat are not affected by this bug

**Comment by probonopd** [comment]
Why would someone want to run a 32-bit AppImage on a 64-bit system? Seems like an odd edge case to me.

**Comment by TheAssassin** [comment]
Whenever there's just 32-bit binaries available that you want to (re-)package, and you don't want to ship 2 AppImages with the exact same contents.

**Comment by probonopd** [comment]
Well, even in those cases it may be advisable to make a 64-bit AppImage that contains both the 32-bit application, any 32-bit libraries it needs to run, and a 64-bit runtime, because those cannot reasonably assumed to be present on all 64-bit systems.

Personally I can live with a 2 GB limitation on 32-bit AppImages running on 64-bit systems and would not invest any time into this, as long as the 2 GB limitation is not there on 32-bit systems running 32-bit AppImages nor 64-bit systems running 64-bit AppImages (the latter is what we mainly care about those days).

**Comment by sigmaboy** [comment]
@probonopd in some cases the 32bit payload in a 64 appimage won't work because of bugs(!?) inside the application. My goal was to build appimages for linux games for lan parties I host. And some of them crash when running from a 64bit appimage. Starting them regularly (without appimage) works perfectly fine with a 64bit OS. Games with the same engine smaller than 2GB work with a 32bit appimage.
This is the reason I'd like to have this issue fixed.

I haven't tested the appimage inside a 32bit linux. Atm I'm downloading 32bit xubuntu. But I think the problem exists also with 32bit linux distributions.
I will report @probonopd

**Comment by probonopd** [comment]
OK, thanks for testing @sigmaboy

**Comment by TheAssassin** [comment]
> So basically everything regarding i386 architecture is affected. Not only 64bit linux with 32bit libraries

I expected that, or rather, if it doesn't work in a 64-bit environment, it won't work in a 32-bit one for sure.

**Comment by sigmaboy** [comment]
Any news on that issue?

**Comment by probonopd** [comment]
As for me, I haven't investigated this: I don't have any 32-bit systems anymore, nor do I have any AppImage over 2 GB. Pull requests welcome though.

**Comment by darealshinji** [comment]
To be honest, for large video games I would just use something like linuxdeploy without creating an AppImage and then put the whole thing into a compressed archive. Or alternatively put only the game engine stuff into an AppImage and store the game files in a single PAK style format (like .vpk or .gcf files).
